service: my-express-app

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1

functions:
  app:
    handler: server.handler
    runtime: nodejs20.x
    events:
      - http:
          path: /
          method: any
      - http:
          path: /{proxy+}
          method: any
